# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20170510_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
