# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170510_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_last_submission',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='has_error',
            field=models.BooleanField(default=False),
        ),
    ]
