# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20170511_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='langid',
            field=models.IntegerField(blank=True, choices=[(0, 'Python'), (1, 'Ruby'), (2, 'Clojure'), (3, 'PHP'), (4, 'Javascript'), (5, 'Scala'), (6, 'Go'), (7, 'C,C++'), (8, 'Java'), (9, 'VB.NET'), (10, 'C#'), (11, 'Bash'), (12, 'Objective-C'), (13, 'MySQL'), (14, 'Perl')], null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
