# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20170516_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='test_time',
            field=models.FloatField(default=2),
        ),
    ]
