# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_assignment_test_langids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='langid',
            field=models.IntegerField(blank=True, choices=[(0, 'Python'), (1, 'Ruby'), (2, 'Clojure'), (3, 'PHP'), (4, 'Javascript'), (5, 'Scala'), (6, 'Go'), (7, 'C'), (8, 'Java'), (9, 'VB.NET'), (10, 'C#'), (11, 'Bash'), (12, 'Objective-C'), (13, 'MySQL'), (14, 'Perl'), (15, 'C++')], null=True),
        ),
    ]
