# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_repository_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.FileField(upload_to='/upload/ef/%Y/%m/%d/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted', to='portal.Assignment')),
            ],
        ),
    ]
