# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_encryptedcode_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
