# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170508_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='asdf', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sid',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
