# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170509_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='langid',
            field=models.IntegerField(choices=[(0, 'Python'), (1, 'Ruby'), (2, 'Clojure'), (3, 'PHP'), (4, 'Javascript'), (5, 'Scala'), (6, 'Go'), (7, 'C,C++'), (8, 'Java'), (9, 'VB.NET'), (10, 'C#'), (11, 'Bash'), (12, 'Objective-C'), (13, 'MySQL'), (14, 'Perl')]),
        ),
    ]
