# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170509_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='github_token',
            new_name='github_username',
        ),
    ]
